spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: realtime-service-test
      auto-offset-reset: earliest
      enable-auto-commit: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://seatflow.ciamlogin.com/test-tenant/v2.0

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

seatflow:
  cors:
    allowed-origins: "*"

logging:
  level:
    root: WARN
    com.seatflow: DEBUG
