spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:seatflow_reservation}
    username: ${DB_USERNAME:seatflow}
    password: ${DB_PASSWORD:seatflow_dev}
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          audiences: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCES:api://seatflow-backend}

event-service:
  base-url: ${EVENT_SERVICE_URL:http://event-service:8083}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.seatflow: INFO
