package com.seatflow.seatmap.integration;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.seatflow.seatmap.model.entity.OutboxEvent;
import com.seatflow.seatmap.repository.OutboxEventRepository;
import com.seatflow.seatmap.repository.SeatRepository;
import com.seatflow.seatmap.repository.VenueRepository;
import com.seatflow.seatmap.repository.VenueSectionRepository;
import com.seatflow.seatmap.web.dto.request.CreateVenueRequest;
import com.seatflow.seatmap.web.dto.request.CreateVenueSectionRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.hasSize;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

@SpringBootTest
@AutoConfigureMockMvc
@Testcontainers
@ActiveProfiles("test")
class SeatMapServiceIntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine")
            .withDatabaseName("seatflow_seatmap_test")
            .withUsername("test")
            .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.flyway.enabled", () -> "true");
        registry.add("spring.kafka.bootstrap-servers", () -> "localhost:9092");
        registry.add("outbox.publisher.fixed-delay-ms", () -> "60000");
    }

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private VenueRepository venueRepository;

    @Autowired
    private VenueSectionRepository sectionRepository;

    @Autowired
    private SeatRepository seatRepository;

    @Autowired
    private OutboxEventRepository outboxEventRepository;

    @MockitoBean
    private JwtDecoder jwtDecoder;

    @BeforeEach
    void cleanUp() {
        outboxEventRepository.deleteAll();
        seatRepository.deleteAll();
        sectionRepository.deleteAll();
        venueRepository.deleteAll();
    }

    @Test
    void shouldCreateVenueAndVerifyOutboxEvent() throws Exception {
        CreateVenueRequest request = new CreateVenueRequest("Integration Theatre", "999 Test Ave", "NYC", "USA", 500);

        MvcResult result = mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j
                                .subject("admin-ext")
                                .claim("email", "admin@test.com")
                                .claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name").value("Integration Theatre"))
                .andExpect(jsonPath("$.capacity").value(500))
                .andReturn();

        // Verify database
        assertThat(venueRepository.existsByNameAndCity("Integration Theatre", "NYC")).isTrue();

        // Verify outbox event
        List<OutboxEvent> outboxEvents = outboxEventRepository.findTop50ByPublishedAtIsNullOrderByCreatedAtAsc();
        assertThat(outboxEvents).hasSize(1);
        assertThat(outboxEvents.getFirst().getEventType()).isEqualTo("VenueCreated");
    }

    @Test
    void shouldCreateSectionWithAutoGeneratedSeats() throws Exception {
        // 1. Create venue first
        CreateVenueRequest venueRequest = new CreateVenueRequest("Seat Grid Venue", "100 Grid Ave", "LA", "USA", 1000);
        MvcResult venueResult = mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j
                                .subject("admin-ext")
                                .claim("email", "admin@test.com")
                                .claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(venueRequest)))
                .andExpect(status().isCreated())
                .andReturn();

        String venueId = objectMapper.readTree(venueResult.getResponse().getContentAsString()).get("id").asText();

        // 2. Create section with 3 rows × 5 seats
        CreateVenueSectionRequest sectionRequest = new CreateVenueSectionRequest("Orchestra", 3, 5);
        mockMvc.perform(post("/api/admin/venues/{venueId}/sections", venueId)
                        .with(jwt().jwt(j -> j
                                .subject("admin-ext")
                                .claim("email", "admin@test.com")
                                .claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(sectionRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name").value("Orchestra"))
                .andExpect(jsonPath("$.activeSeatCount").value(15));

        // 3. Verify seats in database: 3 × 5 = 15 seats
        assertThat(seatRepository.findActiveSeatsForVenueLayout(UUID.fromString(venueId))).hasSize(15);

        // 4. Verify outbox: VenueCreated + VenueSectionCreated
        List<OutboxEvent> events = outboxEventRepository.findTop50ByPublishedAtIsNullOrderByCreatedAtAsc();
        assertThat(events).hasSize(2);
        assertThat(events.stream().map(OutboxEvent::getEventType).toList())
                .containsExactlyInAnyOrder("VenueCreated", "VenueSectionCreated");
    }

    @Test
    void shouldRetrieveVenueLayoutPublicly() throws Exception {
        // Setup: create venue + section + seats
        CreateVenueRequest venueRequest = new CreateVenueRequest("Layout Venue", "200 Layout St", "CHI", "USA", 200);
        MvcResult venueResult = mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j
                                .subject("admin-ext")
                                .claim("email", "admin@test.com")
                                .claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(venueRequest)))
                .andExpect(status().isCreated())
                .andReturn();

        String venueId = objectMapper.readTree(venueResult.getResponse().getContentAsString()).get("id").asText();

        mockMvc.perform(post("/api/admin/venues/{venueId}/sections", venueId)
                        .with(jwt().jwt(j -> j.subject("admin-ext").claim("email", "admin@test.com").claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateVenueSectionRequest("Balcony", 2, 4))))
                .andExpect(status().isCreated());

        // Public layout retrieval — NO authentication required
        mockMvc.perform(get("/api/venues/{venueId}/layout", venueId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.venueId").value(venueId))
                .andExpect(jsonPath("$.name").value("Layout Venue"))
                .andExpect(jsonPath("$.sections").isArray())
                .andExpect(jsonPath("$.sections", hasSize(1)))
                .andExpect(jsonPath("$.sections[0].name").value("Balcony"))
                .andExpect(jsonPath("$.sections[0].seats", hasSize(8))); // 2 × 4 = 8 seats
    }

    @Test
    void shouldListVenuesPubliclyWithPagination() throws Exception {
        // Create two venues
        mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j.subject("admin-ext").claim("email", "admin@test.com").claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateVenueRequest("V1", "A", "NYC", "USA", 100))))
                .andExpect(status().isCreated());
        mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j.subject("admin-ext").claim("email", "admin@test.com").claim("roles", List.of("ROLE_ADMIN")))
                                .authorities(new SimpleGrantedAuthority("ROLE_ADMIN")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateVenueRequest("V2", "B", "LA", "USA", 200))))
                .andExpect(status().isCreated());

        // Public listing — no auth
        mockMvc.perform(get("/api/venues"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content", hasSize(2)))
                .andExpect(jsonPath("$.totalElements").value(2));
    }

    @Test
    void shouldRejectUnauthenticatedAdminAccess() throws Exception {
        mockMvc.perform(post("/api/admin/venues")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateVenueRequest("T", "A", "NYC", "USA", 100))))
                .andExpect(status().isUnauthorized());
    }

    @Test
    void shouldRejectNonAdminAccessToAdminEndpoints() throws Exception {
        mockMvc.perform(post("/api/admin/venues")
                        .with(jwt().jwt(j -> j.subject("user-ext").claim("email", "user@test.com").claim("roles", List.of("ROLE_CUSTOMER")))
                                .authorities(new SimpleGrantedAuthority("ROLE_CUSTOMER")))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(new CreateVenueRequest("T", "A", "NYC", "USA", 100))))
                .andExpect(status().isForbidden());
    }
}
