package com.seatflow.common.domain.enums;

public enum ErrorCode {
    RESOURCE_NOT_FOUND("SF_404_NOT_FOUND"),
    SEAT_ALREADY_RESERVED("SF_409_SEAT_HELD"),
    RESERVATION_EXPIRED("SF_410_RESERVATION_EXPIRED"),
    RESERVATION_LIMIT_EXCEEDED("SF_400_RESERVATION_LIMIT_EXCEEDED"),
    MAX_SEATS_EXCEEDED("SF_400_MAX_SEATS_EXCEEDED"),
    PAYMENT_FAILED("SF_402_PAYMENT_FAILED"),
    PAYMENT_ALREADY_PROCESSED("SF_409_PAYMENT_PROCESSED"),
    UNAUTHORIZED("SF_401_UNAUTHORIZED"),
    FORBIDDEN("SF_403_FORBIDDEN"),
    INVALID_REQUEST("SF_400_INVALID_REQUEST"),
    CONFLICT("SF_409_CONFLICT"),
    INTERNAL_SERVER_ERROR("SF_500_INTERNAL_ERROR"),
    INVALID_ANALYTICS_DATE_RANGE("INVALID_ANALYTICS_DATE_RANGE"),
    ANALYTICS_DATE_RANGE_TOO_LARGE("ANALYTICS_DATE_RANGE_TOO_LARGE"),
    INVALID_ANALYTICS_SORT("INVALID_ANALYTICS_SORT"),
    INVALID_ANALYTICS_LIMIT("INVALID_ANALYTICS_LIMIT");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
