package com.seatflow.event.model.entity;

import com.seatflow.event.model.enums.EventSessionStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.Hibernate;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * One concrete scheduled showing of an {@link Event}.
 *
 * <p>Sessions own schedule fields (starts/ends instants, optional sales window,
 * status, display timezone). Booking and inventory state must reference the
 * session, never duplicate schedule data onto {@link Event}.
 *
 * <p>{@code legacyBackfill} is migration metadata marking the single session
 * generated by V3 for a pre-Phase-12 event. It must never be exposed in
 * customer DTOs. The one-legacy-session-per-event rule is enforced by the
 * partial unique index {@code uq_event_sessions_legacy_event} declared in
 * {@code V3__create_event_sessions_and_backfill.sql}, which cannot be expressed
 * with JPA annotations and therefore lives in DDL only.
 */
@Entity
@Table(
    name = "event_sessions",
    indexes = {
        @Index(name = "idx_event_sessions_event_start", columnList = "event_id, starts_at")
    }
)
@DynamicUpdate
@Getter
@Setter
@Builder
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@ToString(onlyExplicitlyIncluded = true)
public class EventSession {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @ToString.Include
    private UUID id;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    @Column(name = "starts_at", nullable = false)
    @ToString.Include
    private Instant startsAt;

    @Column(name = "ends_at", nullable = false)
    @ToString.Include
    private Instant endsAt;

    @Column(name = "sale_starts_at")
    private Instant saleStartsAt;

    @Column(name = "sale_ends_at")
    private Instant saleEndsAt;

    @Column(nullable = false, length = 32)
    @Enumerated(EnumType.STRING)
    @ToString.Include
    private EventSessionStatus status;

    @Column(length = 64)
    private String timezone;

    @Column(name = "legacy_backfill", nullable = false)
    @Builder.Default
    private Boolean legacyBackfill = Boolean.FALSE;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        EventSession that = (EventSession) o;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
